- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/fish_plugins: fish/fish_plugins
- shell:
  -
    command: fish -c "curl -sL https://git.io/fisher | source; and fisher install jorgebucaran/fisher"
    description: Installing fisher
    quiet: false
- shell:
  -
    command: fish -c "fisher update"
    description: Updating fish plugins
    quiet: false
