- shell:
  -
    command: rm ~/.config/fish/fish_plugins; true
- link:
    ~/.config/fish/config.fish: fish/config.fish
- shell:
  -
    command: fish -c "curl -sL https://git.io/fisher | source; and fisher install jorgebucaran/fisher"
    description: Installing fisher
- link:
    ~/.config/fish/fish_plugins:
      path: fish/fish_plugins
      relink: true
- shell:
  -
    command: fish -c "fisher update"
    description: Updating fish plugins
