- shell:
  - 
    command: sh -c 'git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim || true' 
    description: Install packer, the neovim plugin manager

- link:
    ~/.config/nvim:
      path: nvim
      relink: true
- shell:
  - 
    command: nvim +PackerInstall +qall
    description: Install neovim plugins

