- shell:
  -
    command: fish -c "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm; or true"
    description: Installing tmux plugin manager
- link:
    ~/.tmux.conf:
- shell:
  -
    command: fish -c "test $TMUX; and tmux source ~/.tmux.conf; true"
    description: Reloading tmux conf if inside tmux session
  -
    command: ~/.tmux/plugins/tpm/bin/install_plugins
    description: Installing tmux plugins

