(module dotfiles.core {autoload {nvim aniseed.nvim}})

(set vim.g.colors_name :solarized8)
(set vim.o.timeout true)
(set vim.o.timeoutlen 10)
(set vim.o.number true)
(set vim.o.tabstop 4)
(set vim.o.shiftwidth 4)
(set vim.o.expandtab true)
(set vim.o.background :dark)
